image:
  file: .gitpod.Dockerfile
ports:
- port: 8002
  visibility: public
- port: 9001
- port: 15672
  visibility: public
vscode:
  extensions:
    - TabNine.tabnine-vscode@3.4.14
    - felixfbecker.php-debug@1.16.0
github:
  prebuilds:
    master: true
    branches: true
tasks:
  - openMode: tab-after
    name: "Services"
    init: sudo chown -R gitpod:gitpod /home/gitpod/.config/composer;
          cd $GITPOD_REPO_ROOT &&
          composer config -g -a http-basic.repo.magento.com ${MAGENTO_COMPOSER_AUTH_USER} ${MAGENTO_COMPOSER_AUTH_PASS} &&
          composer create-project --no-interaction --no-progress --repository-url=https://mirror.mage-os.org/ magento/project-community-edition=${MAGENTO_VERSION} magento2 &&
          cd magento2 && cp -avr .* $GITPOD_REPO_ROOT;
          cd $GITPOD_REPO_ROOT && rm -r -f magento2 && git checkout -- .gitignore;
    command: sudo sed -i 's#$GITPOD_REPO_ROOT#'$GITPOD_REPO_ROOT'#g' /etc/nginx/nginx.conf &&
             sudo sed -i 's#$GITPOD_REPO_ROOT#'$GITPOD_REPO_ROOT'#g' /etc/supervisor/conf.d/sp-php-fpm.conf &&
             sudo sed -i 's#$PHP_VERSION#'$PHP_VERSION'#g' /etc/supervisor/conf.d/sp-php-fpm.conf &&
             sudo cp $GITPOD_REPO_ROOT/gitpod/sp-redis.conf /etc/supervisor/conf.d/redis.conf &&
             sudo cp $GITPOD_REPO_ROOT/gitpod/sp-elasticsearch.conf /etc/supervisor/conf.d/elasticsearch.conf &&
             sudo sed -i 's/^\(\[supervisord\]\)$/\1\nnodaemon=true/' /etc/supervisor/supervisord.conf &&
             service nginx start &
             sudo mv /var/lib/mysql $GITPOD_REPO_ROOT/;
             sed -i 's#/var/lib/mysql#'$GITPOD_REPO_ROOT'/mysql#g' /etc/mysql/conf.d/mysqld.cnf;
             sudo sed -i 's#/var/lib/mysql#'$GITPOD_REPO_ROOT'/mysql#g' /etc/supervisor/conf.d/mysql.conf;
             sudo /etc/init.d/supervisor start & \ ;
             test ! -f $GITPOD_REPO_ROOT/gitpod/db-installed.flag && $GITPOD_REPO_ROOT/gitpod/m2-install.sh;
             url=$(gp url | awk -F"//" {'print $2'}) && url="https://m2remote-"$url"/";
             php bin/magento config:set web/unsecure/base_url $url;
             php bin/magento config:set web/unsecure/base_link_url $url;
             php bin/magento config:set web/secure/base_url $url;
             php bin/magento sampledata:deploy;
             php bin/magento setup:upgrade;
             php bin/magento setup:di:compile;
             php bin/magento setup:static-content:deploy;
# tasks:
#   - openMode: split-right
#     name: "Installer and Services menu"
#     command: cat /etc/lighthouse.conf >> /home/gitpod/.bashrc && chmod a+rwx menu.sh && ./menu.sh
#   - openMode: tab-after
#     name: "Services"
#     command: service nginx start &
#              rm -f /etc/php/7.4/cli/conf.d/20-tideways.ini && rm -f /etc/php/7.4/fpm/conf.d/20-tideways.ini &&
#              sudo cp /workspace/magento2gitpod/sp-redis.conf /etc/supervisor/conf.d/redis.conf &&
#              sudo cp /workspace/magento2gitpod/sp-elasticsearch.conf /etc/supervisor/conf.d/elasticsearch.conf &&
#              sudo sed -i 's/^\(\[supervisord\]\)$/\1\nnodaemon=true/' /etc/supervisor/supervisord.conf &&
#              sudo /etc/init.d/supervisor start & \
#              sleep 30;
#              sudo supervisorctl stop mysql;
#              sudo mv /var/lib/mysql /workspace/magento2gitpod/;
#              sed -i 's#/var/lib/mysql#/workspace/magento2gitpod/mysql#g' /etc/mysql/conf.d/mysqld.cnf;
#              sudo sed -i 's#/var/lib/mysql#/workspace/magento2gitpod/mysql#g' /etc/supervisor/conf.d/mysql.conf;
#              sudo supervisorctl update;
#              sudo supervisorctl reload;
#              sudo /etc/init.d/rabbitmq-server start & \
#              sleep 15;
#              sudo rabbitmq-plugins enable rabbitmq_management;
#              sudo rabbitmqctl add_user guest guest;
#              sudo rabbitmqctl set_user_tags guest administrator;
#              sudo rabbitmqctl set_permissions -p / guest ".*" ".*" ".*";
#   - name: "Terminal/SSH Start here"
#     command: source /etc/lighthouse.conf;clear;echo "Good luck. Happy coding and testing!"
